version: "3.9"
services:
  ctfd-nginx-proxy:
    image: nginx:stable-alpine
    container_name: ctfd-nginx-proxy
    restart: unless-stopped
    volumes:
      - ./CTFd/plugins/my-plugin/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./CTFd/plugins/my-plugin/nginx/token_map.conf:/etc/nginx/token_map.conf:ro
    ports:
      - "8008:8008"
    depends_on:
      - ctfd



      - ./CTFd/plugins/my-plugin/ssh/init-ssh.sh:/init-ssh.sh
      - ./CTFd/plugins/my-plugin/ssh/ctfd_ssh_keys:/ssh/.ssh  # or any path the container user can write to
    entrypoint: ["/init-ssh.sh"]
    command: ["docker-entrypoint.sh"]  # original entrypoint
    user: root