class RuntimeConfig:
    WORKER_NODES = []
    MAX_ACTIVE_CONTAINERS_PER_GROUP = 3
    CONTAINER_SUSPENSION_INTERVAL = 600
    DOCKER_CONTAINER_LIFETIME = 3600
    MEM_LIMIT_PER_CONTAINER = 512 * (1024 ** 2)
    MAX_SPARE_RAM = 1024 * (1024 ** 2)
    DOCKER_CONTAINER_CPU_QUOTA = 50000
    DOCKER_CONTAINER_NETWORK = "ctfd-challenges"
    INTERNAL_PORT_RANGE_START=50000
    INTERNAL_PORT_RANGE_END=60000