user nginx;
worker_processes auto;
worker_cpu_affinity auto;
pid /run/nginx.pid;
error_log /var/log/nginx/error.log;
include /etc/nginx/modules-enabled/*.conf;

events {
    worker_connections 768;
}

http {
    sendfile on;
    tcp_nopush on;
    types_hash_max_size 2048;
    server_tokens off;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;

    access_log /var/log/nginx/access.log;
    gzip on;

    include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/sites-enabled/*;

    map $host $token {
        "~^([a-f0-9]{12})\." $1;
        default "";
    }

    resolver 127.0.0.11 valid=30s ipv6=off;
    resolver_timeout 1s;

    include /etc/nginx/data/data_map.conf;

    proxy_cache_path /tmp/nginx_token_cache levels=1 keys_zone=token_cache:1m inactive=60s;

    server {
        listen 8008;
        include /etc/nginx/data/server_name.conf;

        location / {
            auth_request /resolve-backend;
            auth_request_set $backend $upstream_http_x_backend;

            # auth_request returns 403 when /resolve-backend returns 404
            error_page 403 =302 http://$ctfd_host/challenge-unavailable/404;

            mirror /challenge-keepalive;
            mirror_request_body off;

            proxy_pass http://$backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_intercept_errors on;
            error_page 502 =302 http://$ctfd_host/challenge-unavailable/$token;
        }

        location = /resolve-backend {
            internal;
            proxy_pass http://$ctfd_host/docker/api/token/$token/backend;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_set_header X-Real-IP $remote_addr;

            proxy_cache token_cache;
            proxy_cache_valid 200 30s;
            proxy_cache_valid 404 5s;
            proxy_cache_key $token;

            proxy_cache_use_stale off;
        }

        location = /challenge-keepalive {
            internal;
            proxy_pass http://$ctfd_host/docker/api/token/$token/keepalive;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_ignore_client_abort on;
            charset off;
        }
    }
}
stream {
    resolver 127.0.0.11 valid=30s ipv6=off;

    log_format stream_basic '$remote_addr [$time_local] '
                            '$protocol $status $bytes_sent '
                            '$session_time "$upstream_addr"';
    access_log /var/log/nginx/stream_access.log stream_basic;

    include /etc/nginx/data/stream_map.conf;
}